# Generated by Django 5.2.7 on 2025-10-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0002_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='day_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
