# Generated by Django 5.2.7 on 2025-10-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0003_alter_lesson_day_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='day_number',
            field=models.PositiveIntegerField(),
        ),
    ]
