# Generated by Django 5.2.7 on 2025-10-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0004_alter_lesson_day_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.ImageField(default=None, upload_to='product_images/'),
        ),
    ]
