# Generated by Django 5.2.7 on 2025-10-18 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs_app', '0002_user_creation_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_creation',
        ),
    ]
